FROM geo-jupyter

ENV DATACUBE_VERSION=develop

ENV LC_ALL=C.UTF-8
ENV LANG="$LC_ALL"

## Datacube

RUN pip3 install --no-cache --upgrade \
    'git+https://github.com/opendatacube/datacube-core.git@'"${DATACUBE_VERSION}"'#egg=datacube[s3,test]'

# clean up
RUN apt-get clean && \
rm -rf /var/lib/apt/lists/*

# switch to notebook user
USER "$NB_USER"
