FROM alpine
MAINTAINER Kirill Kouzoubov

RUN apk update &&\
    apk add python3 linux-pam nodejs nodejs-npm docker &&\
    pip3 install --no-cache-dir\
     jupyterhub \
     dockerspawner \
     oauthenticator &&\
    npm install -g configurable-http-proxy

ADD ./config/userlist /srv/jupyterhub/
ADD ./jupyterhub_config.py /srv/jupyterhub/